# Site settings
title: Rena Sung
email: res176@pitt.edu
description: > # this means to ignore newlines until "baseurl:"
  Ph.D. Candidate, Graduate School of Public and International Affairs, University of Pittsburgh

google_site_verification: "wdXZVmqEbo0LcpusSS51Tuc4G-uF9w9NDBE5g57xHbM"
  
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "renasung.github.io" # the base hostname & protocol for your site

github_username:  renasung
twitter_username: sung315

permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap
  
# Build settings
markdown: kramdown
theme: minima
